import assert from "node:assert/strict";
import test from "node:test";
import { renderForgePlatformHtml } from "./forgePlatformUi.js";

test("forge platform html includes skia brand and orchestrate route", () => {
  const html = renderForgePlatformHtml();
  assert.ok(html.includes("SKIA FORGE"));
  assert.ok(html.includes("/api/forge/orchestrate"));
  assert.ok(html.includes("/api/forge/module/"));
  assert.ok(html.includes("/api/forge/modules/status"));
  assert.ok(html.includes("api/forge/context/structure"));
  assert.ok(html.includes("api/forge/context/semantic-chunks"));
  assert.ok(html.includes("api/forge/context/embed/stats"));
  assert.ok(html.includes("api/forge/context/embed/index"));
  assert.ok(html.includes("api/forge/context/embed/queue"));
  assert.ok(html.includes("api/forge/context/embed/jobs"));
  assert.ok(html.includes("api/forge/context/embed/search"));
  assert.ok(html.includes("api/forge/context/retrieve"));
  assert.ok(html.includes("api/forge/agent/plan"));
  assert.ok(html.includes("api/forge/agent/execute"));
  assert.ok(html.includes("selfCorrect"));
  assert.ok(html.includes("/api/forge/mode"));
  assert.ok(html.includes("/api/forge/approval-token"));
  assert.ok(html.includes("/api/forge/approval-token/stats"));
  assert.ok(html.includes("/api/forge/governance/intents/status"));
  assert.ok(html.includes("/api/forge/sovereign-posture"));
  assert.ok(html.includes("/api/forge/lockdown"));
  assert.ok(html.includes("/api/forge/governance/telemetry"));
  assert.ok(html.includes("/api/forge/control-plane"));
  assert.ok(html.includes("/api/forge/control-plane/remediate"));
  assert.ok(html.includes("/api/forge/control-plane/remediate/recommended"));
  assert.ok(html.includes("/api/forge/orchestrate/preview"));
  assert.ok(html.includes("controlPlaneAlerts"));
  assert.ok(html.includes("controlPlaneRecommendations"));
  assert.ok(html.includes("approvalToken"));
  assert.ok(html.includes("approvalPurpose"));
  assert.ok(html.includes("approvalTokenStatsResult"));
  assert.ok(html.includes("intentSignature"));
  assert.ok(html.includes("intentNonce"));
  assert.ok(html.includes("intentTs"));
  assert.ok(html.includes("sovereignPostureResult"));
  assert.ok(html.includes("toggleLockdown"));
  assert.ok(html.includes("autonomous"));
  assert.ok(html.includes("#d4af37"));
});
